#!/usr/bin/env python3
"""B4/D1 appendix exhibit: ledger evolution for 2-3 agents — the L1 posterior
table and L2 lessons BEFORE the extension (deterministic replay of the prefix
only) vs AFTER (replay of all records; final lessons from tei/ledger.json).

Also emits paper/tables/ledger_exhibit.tex (booktabs) and ledger_exhibit.json
as the number source. Deterministic; no LLM calls.
"""
import json
import os
import sys

ROOT = os.path.expanduser("~/swebench-agents")
AGENTS = os.path.join(ROOT, "agents")
sys.path.insert(0, ROOT)
from bcl import BayesianCreditLedger, ALL_FAMS  # noqa: E402
from tei_pipeline import load_candidates, VAR0_DEFAULT  # noqa: E402

EXHIBIT_AGENTS = ["01_livesweagent", "12_kgcompass", "27_agentless"]


def posterior_rows(L):
    rows = []
    for fam in ALL_FAMS:
        cell = L.cells.get((fam, L.weak)) or L.fam_agg.get(fam)
        if not cell or cell.n == 0:
            continue
        a, b = cell.beta_params()
        m, _ = cell.post_mean_var()
        rows.append({"family": fam, "mean_delta": round(m, 4),
                     "p_pos": round(a / (a + b), 2), "n": cell.n})
    return rows


def snapshot(d, upto=None):
    tei = os.path.join(AGENTS, d, "tei")
    base = json.load(open(os.path.join(tei, "baseline_eval.json")))
    ob = json.load(open(os.path.join(tei, "onboarding.json")))
    recs = load_candidates(tei)
    if upto == "prefix":
        recs = [r for r in recs if "arm" not in r]
    L = BayesianCreditLedger("/tmp/_exhibit_scratch",
                             base.get("weakest_dimension") or "execution_accuracy",
                             VAR0_DEFAULT, seed=ob["rank"])
    os.makedirs("/tmp/_exhibit_scratch", exist_ok=True)
    L.lessons = []          # lessons are not replayable; handled separately
    for r in recs:
        L.ingest(r, log=False)
    return posterior_rows(L), len(recs)


def lessons_timeline(d):
    p = os.path.join(AGENTS, d, "tei", "ledger_log.jsonl")
    ops = []
    if os.path.isfile(p):
        for line in open(p):
            e = json.loads(line)
            if e.get("ev") == "lesson_op":
                ops.append({k: v for k, v in e.items() if k != "ev"})
    final = []
    lp = os.path.join(AGENTS, d, "tei", "ledger.json")
    if os.path.isfile(lp):
        final = json.load(open(lp)).get("lessons", [])
    return ops, final


def tex_escape(s):
    return (str(s).replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")
            .replace("#", "\\#").replace("$", "\\$"))


def main():
    out = {}
    tex = ["% auto-generated by ledger_exhibit.py — do not edit",
           "\\begin{tabular}{llrrr}", "\\toprule",
           "agent & family & mean $\\Delta$ & $P(\\Delta>0)$ & $n$ \\\\"]
    for d in EXHIBIT_AGENTS:
        before, n_pre = snapshot(d, upto="prefix")
        after, n_all = snapshot(d)
        ops, final_lessons = lessons_timeline(d)
        out[d] = {"n_prefix": n_pre, "n_final": n_all,
                  "posteriors_before": before, "posteriors_after": after,
                  "n_lesson_ops": len(ops), "lesson_ops": ops[:40],
                  "final_lessons": final_lessons}
        tex.append("\\midrule")
        tex.append(f"\\multicolumn{{5}}{{l}}{{\\textbf{{{tex_escape(d)}}} — before extension "
                   f"(prefix, $n={n_pre}$)}} \\\\")
        for r in sorted(before, key=lambda x: -x["mean_delta"])[:5]:
            tex.append(f" & {tex_escape(r['family'])} & {r['mean_delta']:+.4f} & "
                       f"{r['p_pos']:.2f} & {r['n']} \\\\")
        tex.append(f"\\multicolumn{{5}}{{l}}{{\\quad after extension ($n={n_all}$; "
                   f"{len(ops)} lesson delta-ops; {len(final_lessons)} final lessons)}} \\\\")
        for r in sorted(after, key=lambda x: -x["mean_delta"])[:5]:
            tex.append(f" & {tex_escape(r['family'])} & {r['mean_delta']:+.4f} & "
                       f"{r['p_pos']:.2f} & {r['n']} \\\\")
        print(f"{d}: prefix n={n_pre} -> final n={n_all}, lesson ops={len(ops)}, "
              f"final lessons={len(final_lessons)}")
    tex += ["\\bottomrule", "\\end{tabular}"]
    json.dump(out, open(os.path.join(ROOT, "ledger_exhibit.json"), "w"), indent=1)
    os.makedirs(os.path.join(ROOT, "paper", "tables"), exist_ok=True)
    open(os.path.join(ROOT, "paper", "tables", "ledger_exhibit.tex"), "w").write("\n".join(tex) + "\n")
    print("wrote ledger_exhibit.json + paper/tables/ledger_exhibit.tex")


if __name__ == "__main__":
    main()
