#!/usr/bin/env python3
"""P1.2: budget-matched RANDOM-PROPOSAL control arm (fixed 10-agent subsample).

Per agent: N unguided proposal iterations (N = that agent's structural budget /
2.5, min 12 — matching the real run's applied-patch yield), generated by the
same model with NO diagnosis, NO failure modes, NO target dimension; applied
through the SAME pre-gated apply path onto branch random-v1; rubric-scored with
the SAME batch prompt; then the SAME blinded protocol vs baseline (seed 13).
Comparison target: TEI's diagnosis-guided arm on the same agents.
"""
import json
import os
import random
import subprocess
import sys

sys.path.insert(0, os.path.expanduser("~/swebench-agents"))
import tei_pipeline as T
from tei_pipeline import call_json, BUDGET, clamp_score, aggregate, evidence_pack
import blind_reval as BR

ROOT = os.path.expanduser("~/swebench-agents")
AGENTS = os.path.join(ROOT, "agents")
TEN = ['05_joycode', '06_lingxi', '07_moatlesstools', '09_agentscope',
       '11_experepair', '15_composioswekit', '18_codefusecgm',
       '19_agentlesslite', '22_orcaloca', '24_swefixer']
K = 5
rng = random.Random(13)


def sh(cmd, cwd):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def main():
    results = []
    for d in TEN:
        repo = os.path.join(AGENTS, d)
        ob = json.load(open(os.path.join(repo, "tei", "onboarding.json")))
        base = json.load(open(os.path.join(repo, "tei", "baseline_eval.json")))
        res = json.load(open(os.path.join(repo, "tei", "result.json")))
        base_sha = ob["repo_sha"]
        cur = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], repo).stdout.strip()
        sh(["git", "checkout", "-q", "-B", "random-v1", base_sha], repo)
        try:
            n_iters = 12
            ev = evidence_pack(repo, ob)
            applied = 0
            cand_scores = []
            for batch in range(0, n_iters, 6):
                n = min(6, n_iters - batch)
                gen = f"""Propose {n} DISTINCT small code changes to this software repository. You are given
only general context; you have NO information about what fails or what should improve. Propose
plausible, generic maintenance-style edits (any part of the code), each as an exact replacement:
'file' (path relative to repo root), 'find' (exact snippet occurring verbatim, <=15 lines),
'replace' (new text). Do not target any specific behavior.

REPOSITORY CONTEXT:
{ev}

JSON: {{"candidates":[{{"file":"...","find":"...","replace":"...","note":"one line"}}]}}"""
                try:
                    cands = call_json(gen, max_out=8000).get("candidates", [])[:n]
                except Exception as e:
                    print(f"  gen failed {d}: {e}"); continue
                for c in cands:
                    ok, note = T.apply_patch(repo, c, f"rand-{batch}")
                    applied += bool(ok)
                # rubric-score the batch with the SAME scoring prompt
                slim = [{"i": i, "technique": "unguided maintenance edit",
                         "target_failure_mode": "none (control)",
                         "change": (str(c.get("replace"))[:300] if c.get("replace") else str(c.get("note", "")))[:300]}
                        for i, c in enumerate(cands)]
                score = f"""Strictly score each candidate VERSION of this SWE-bench agent on the TEI rubric.

SYSTEM: {ob['system']} ({ob['resolve_rate']}% resolved). Phase: structural.
BASELINE dimensions: {json.dumps(base.get('dimensions'))} (aggregate {base.get('aggregate')})
BASELINE per-probe: {json.dumps(base.get('probe_scores'))}
DIAGNOSED FAILURE MODES: {json.dumps([f.get('name') for f in base.get('failure_modes', [])])}

CANDIDATE VERSIONS:
{json.dumps(slim, indent=1)}

Be strict and differentiating: most targeted changes move a dimension by a small amount
(±0.01-0.06); some make things worse and MUST score below baseline. No value may exceed 0.99.

JSON: {{"results":[{{"i":0,"dimensions":{{"target_alignment":0.0,"reasoning_soundness":0.0,"execution_accuracy":0.0,"output_integrity":0.0}},"why":"one sentence"}}]}}"""
                try:
                    scored = call_json(score, max_out=6000).get("results", [])
                except Exception as e:
                    print(f"  score failed {d}: {e}"); scored = []
                for s in scored:
                    agg = aggregate({k: clamp_score(v) for k, v in (s.get("dimensions") or {}).items()})
                    if agg is not None:
                        cand_scores.append(agg)
            best_rand = max(cand_scores) if cand_scores else None
            # blinded protocol vs baseline on the random branch's real diff
            files = BR.changed_files(repo, base_sha)
            pairs = [(p, *e) for p in files if (e := BR.excerpt_pair(repo, base_sha, p))]
            probes = [p["instance_id"] for p in base.get("probes", [])][:4]
            votes = []
            for k in range(K):
                if not pairs:
                    break
                flip = rng.random() < 0.5
                blocks = [f"### file: {path}\n--- VERSION 1 ---\n{(aft if flip else bef)}\n"
                          f"--- VERSION 2 ---\n{(bef if flip else aft)}"
                          for path, bef, aft in pairs]
                prompt = f"""You are comparing two versions of the same software-engineering agent system
({ob['system']}; its job: resolve real GitHub issues, SWE-bench style). Below, for each shown file,
are the two versions' contents in the regions where they differ. You are NOT told which version is
older; judge only what you see.

Representative task instances this agent faces: {', '.join(probes)}.

{chr(10).join(blocks)}

Which version is more likely to resolve such issues correctly end-to-end? If too trivial or
ambiguous to matter, say tie.

Return ONLY JSON: {{"better": "1" | "2" | "tie", "confidence": 0.0, "reason": "one sentence"}}"""
                try:
                    v = call_json(prompt, max_out=1200)
                except Exception as e:
                    votes.append({"error": str(e)[:60]}); continue
                pick = str(v.get("better", "")).strip()
                votes.append({"vote": ("random" if pick == ("1" if flip else "2") else
                                       "baseline" if pick in ("1", "2") else "tie")})
            pv = sum(1 for v in votes if v.get("vote") == "random")
            bv = sum(1 for v in votes if v.get("vote") == "baseline")
            results.append({
                "agent": d, "n_proposals": n_iters, "n_applied": applied,
                "rubric_scores": cand_scores,
                "rubric_best_delta": (round(best_rand - base["aggregate"], 4)
                                      if best_rand is not None else None),
                "tei_rubric_delta": res.get("shipped_delta"),
                "blind_random": pv, "blind_baseline": bv,
                "blind_tie": len(votes) - pv - bv})
            print(f"{d:26s} applied {applied}/{n_iters} | rand Δ "
                  f"{results[-1]['rubric_best_delta']} vs TEI {res.get('shipped_delta'):+.4f} | "
                  f"blind {pv}/{bv} [${BUDGET.conservative:.2f}]", flush=True)
        finally:
            sh(["git", "checkout", "-q", cur or "tei-v7"], repo)
    json.dump({"seed": 13, "results": results, "budget": BUDGET.as_dict()},
              open(os.path.join(ROOT, "random_arm.json"), "w"), indent=1)
    ok = [r for r in results if r.get("rubric_best_delta") is not None]
    import numpy as np
    tei_w = sum(1 for r in ok if r["tei_rubric_delta"] > r["rubric_best_delta"])
    print(f"\nRANDOM ARM: TEI rubric delta beats random-best on {tei_w}/{len(ok)} agents; "
          f"random mean best Δ {np.mean([r['rubric_best_delta'] for r in ok]):+.4f} vs "
          f"TEI {np.mean([r['tei_rubric_delta'] for r in ok]):+.4f}")
    print("budget:", json.dumps(BUDGET.as_dict()))


if __name__ == "__main__":
    main()
